// The module 'vscode' contains the VS Code extensibility API
// Import the module and reference it with the alias vscode in your code below
import * as vscode from 'vscode';

// this method is called when your extension is activated
// your extension is activated the very first time the command is executed
export function activate(context: vscode.ExtensionContext) {
	let data = {
		'player': ['galaxy', 'room', 'module', 'longrange', 'occupiedship', 'hasdiscount', 'ship', 'name', 'input', 'maxscanlevel', 'hascommission', 'conversation', 'sector', 'age', 'zone', 'station', 'timewarp', 'cluster', 'scanlevel', 'debug', 'platform', 'container', 'isscreenshotmode', 'flightassist', 'rawname', 'target', 'autopilottarget', 'isinconversation', 'speakpriority', 'chardensity', 'entity', 'isvrmode', 'controlled', 'hasclothingmod', 'screenshotmode', 'headquarters', 'hasactivemission', 'systemtime', 'computer', 'isvrversion', 'money', 'blueprints', 'autosave', 'activity', 'conversationactor', 'hasscanner', 'encyclopedia', 'canteleportto', 'exists'] ,
		'exists': ['boolean'] ,
		'name': ['string'] ,
		'rawname': ['string'] ,
		'age': ['time'] ,
		'systemtime': ['string'] ,
		'string': ['string'] ,
		'money': ['money', 'formatted', 'datatype'] ,
		'container': ['integer', 'container', 'macro'] ,
		'ship': ['length'] ,
		'station': ['isfactionheadquarters', 'buildstorage', 'iswharf', 'isshipyard', 'isequipmentdock', 'ispiratebase', 'paidbuildplot', 'isdefencestation', 'station', 'isheadquarters', 'buildplot', 'istradestation'] ,
		'occupiedship': ['ship'] ,
		'controlled': ['controllable', 'object'] ,
		'platform': ['dockingbay'] ,
		'room': ['actors', 'isprivate', 'hascontrolpanel', 'ischairslot', 'room', 'slotcontext', 'type', 'freemissionactorslot', 'chairapproachslot', 'chairbaseslot', 'islocked', 'controlpositions', 'numfreeactorslots', 'walkablemodule', 'dockarea', 'controlposition', 'buildmodule'] ,
		'entity': ['isshadyguy', 'neededexperience', 'inventory', 'experienceprogress', 'shouldwarnplayer', 'assignedcontrolled', 'stock', 'skill', 'tradesvisible', 'commandaction', 'combinedskill', 'dockarea', 'controlled', 'buildmodule', 'command', 'boolean', 'skillsvisible', 'istradecomputer', 'cancraft', 'shouldinformplayer', 'walkablemodule', 'potentialskill'] ,
		'zone': ['istempzone', 'isnormalzone', 'size', 'policefaction', 'zone', 'adjacentzones', 'haspriority'] ,
		'sector': ['iscontestedby', 'sector', 'policefaction', 'iscontested', 'contestingfactions'] ,
		'cluster': ['ispresentation', 'isnormalcluster', 'cluster', 'systemid'] ,
		'galaxy': ['galaxy'] ,
		'computer': ['entity'] ,
		'headquarters': ['station'] ,
		'canteleportto': ['controllable'] ,
		'controllable': ['defaultorder', 'ischairslot', 'shiptrader', 'longrange', 'tradeorders', 'controlposts', 'maxscanlevel', 'nextorder', 'assignedcontrolentity', 'engineer', 'defencenpc', 'subordinates', 'controlpositions', 'shadyguy', 'allsubordinates', 'assignedpilot', 'hackerprobe', 'canhavecontrolentity', 'canhavecommander', 'controlroom', 'controlentity', 'controllable', 'chairapproachslot', 'combinedskill', 'chairbaseslot', 'orders', 'pilot', 'controlposition', 'order', 'boolean', 'wing', 'controlpostslot', 'commander', 'commanderentity', 'software', 'tradenpc', 'tradecomputer', 'assignment', 'hasscanner', 'people'] ,
		'activity': ['@value', 'datatype', 'activity'] ,
		'target': ['integer', 'destructible', 'object'] ,
		'autopilottarget': ['object'] ,
		'conversation': ['string'] ,
		'isinconversation': ['boolean'] ,
		'conversationactor': ['entity'] ,
		'hasactivemission': ['boolean'] ,
		'hascommission': ['faction', 'container'] ,
		'faction': ['faction', 'boolean'] ,
		'id': ['constructionplanentryid', 'string', 'exists'] ,
		'hasdiscount': ['faction', 'container'] ,
		'': ['response', 'random', 'name', 'shouldaskplayer', 'faction', ']', 'list', 'min', 'component', 'cycle', 'product', 'rawname', 'mid', 'description', 'level', 'id', 'combinedskill', 'primary', 'resource', 'count', 'secondary', 'max', 'potentialskill', 'exists'] ,
		'blueprints': ['ware'] ,
		'ware': ['ware', 'max'] ,
		'any': ['secondary', 'method', 'cycle', 'primary', 'resource', 'product', 'exists'] ,
		'method': ['string'] ,
		'cycle': ['time', 'efficiency'] ,
		'efficiency': ['float'] ,
		'time': ['time', 'formatted', 'datatype'] ,
		'resource': ['wares', 'efficiency'] ,
		'wares': ['warelist', 'wareamountlist'] ,
		'primary': ['wares', 'boolean', 'hitpoints', 'efficiency', 'length'] ,
		'secondary': ['wares', 'boolean', 'hitpoints', 'efficiency', 'length'] ,
		'product': ['amount', 'efficiency'] ,
		'amount': ['integer'] ,
		'hasscanner': ['boolean'] ,
		'scanlevel': ['integer'] ,
		'maxscanlevel': ['integer'] ,
		'longrange': ['boolean'] ,
		'debug': ['boolean'] ,
		'isscreenshotmode': ['boolean'] ,
		'screenshotmode': ['string'] ,
		'isvrversion': ['boolean'] ,
		'isvrmode': ['boolean'] ,
		'chardensity': ['float'] ,
		'module': ['string', 'module'] ,
		'speakpriority': ['integer'] ,
		'input': ['controller', 'vivecontroller', 'mousesteering', 'vrcontroller', 'oculustouch', 'boosttoggle'] ,
		'controller': ['boolean'] ,
		'boosttoggle': ['boolean'] ,
		'mousesteering': ['boolean', 'permanent'] ,
		'permanent': ['boolean'] ,
		'oculustouch': ['boolean'] ,
		'vivecontroller': ['boolean'] ,
		'vrcontroller': ['boolean'] ,
		'timewarp': ['factor', 'active', 'available'] ,
		'active': ['boolean'] ,
		'available': ['boolean'] ,
		'factor': ['time'] ,
		'autosave': ['active', 'available'] ,
		'flightassist': ['boolean'] ,
		'hasclothingmod': ['ware', 'boolean'] ,
		'null': ['isclass', 'isrealclass', 'isconstruction', 'iswreck', 'isoperational', 'available', 'datatype', 'exists'] ,
		'isoperational': ['boolean'] ,
		'iswreck': ['boolean'] ,
		'isconstruction': ['boolean'] ,
		'isclass': ['list', 'class'] ,
		'class': ['boolean'] ,
		'<classname>': ['boolean'] ,
		'list': ['list', 'boolean'] ,
		'isrealclass': ['list', 'class'] ,
		'position': ['length'] ,
		'[$x, $y, $z]': ['position', 'vector'] ,
		'vector': ['length'] ,
		'rotation': ['pitch', 'roll', 'rotation', '[$yaw, $pitch, $roll]', 'inverse', 'yaw', 'datatype'] ,
		'[$yaw, $pitch, $roll]': ['rotation'] ,
		'readtext': ['textpage'] ,
		'textpage': ['textid'] ,
		'textid': ['string'] ,
		'stat': ['@id'] ,
		'@id': ['ware', 'numeric', 'warelist', 'race', 'faction', 'unlock'] ,
		'datatype': ['weaponmode', 'rotation', 'keyword', 'purpose', 'trade', 'npctemplate', 'formationshape', 'string', 'loadout', 'largeint', 'orderstate', 'position', 'cuestate', 'attention', 'componentslot', 'faction', 'dockstate', 'group', 'tag', 'float', 'operation', 'flightcontrolmodel', 'controlpost', 'roompopulationtype', 'unitcategory', 'skilltype', 'missiontype', 'killmethod', 'missiongroup', 'list', 'component', 'xmlkeyword', 'entityrole', 'alertlevel', 'controlpaneltype', 'flightbehaviour', 'boardingphase', 'constructionsequence', 'licence', 'isnumeric', 'isstring', 'relationchangereason', 'signalleaktype', 'datatype', 'length', 'objective', 'unlock', 'largefloat', 'null', 'commandaction', 'table', 'level', 'shiptype', 'boardingbehaviour', 'waretransport', 'controlposition', 'race', 'class', 'quadrant', 'roomtype', 'build', 'order', 'componentstate', 'command', 'hitpoints', 'integer', 'money', 'time', 'ware', 'vector', 'activity', 'entitytype', 'macro', 'assignment', 'moodlevel', 'cue', 'deployablecategory', 'angle'] ,
		'integer': ['datatype'] ,
		'largeint': ['datatype'] ,
		'float': ['datatype'] ,
		'length': ['datatype', 'length'] ,
		'angle': ['datatype'] ,
		'hitpoints': ['datatype'] ,
		'largefloat': ['datatype'] ,
		'component': ['boolean'] ,
		'trade': ['minamount', 'minprice', 'quantityfactor', 'amount', 'trade', 'isbuyerpassive', 'iswareexchange', 'buyer', 'available', 'relativeprice', 'transferredamount', 'bundle', 'exchangepartner', 'offeramount', 'desiredamount', 'ispassive', 'restriction', 'destroyedamount', 'datatype', 'ismission', 'isshiptoship', 'owner', 'sellfree', 'issellerpassive', 'unitprice', 'ispricelocked', 'unbundle', 'minvolume', 'ware', 'price', 'volume', 'stocklevel', 'buyfree', 'seller', 'exists'] ,
		'build': ['rotation', 'loadout', 'position', 'faction', 'zone', 'buildprocessor', 'isexpansion', 'construction', 'constructionsequence', 'mayrequireconstructionvessel', 'exists', 'buildobject', 'buildmodule', 'build', 'base', 'boolean', 'price', 'isshipbuild', 'macro', 'isupgrade', 'consumables', 'object'] ,
		'operation': ['operation', 'boardinginsertionthreshold', 'attackers', 'boardingapproachthreshold', 'allmarinesdispatched', 'boardingphase', 'boardee', 'marines', 'datatype', 'exists'] ,
		'order': ['build', 'order', 'rawname', 'canplayercancel', 'isparameditable', 'operation', 'isrunning', 'state', 'description', 'trade', 'id', 'isinfinite', 'istradecomputer', 'name', 'datatype', 'exists', 'object'] ,
		'cue': ['actors', 'boolean', 'actor'] ,
		'keyword': ['datatype'] ,
		'xmlkeyword': ['datatype'] ,
		'componentstate': ['datatype', '@value'] ,
		'killmethod': ['datatype', '@value'] ,
		'relationchangereason': ['name', 'datatype', '@value'] ,
		'attention': ['datatype', 'attention', '@value'] ,
		'flightbehaviour': ['datatype', '@value'] ,
		'flightcontrolmodel': ['datatype', '@value'] ,
		'formationshape': ['formationshape', 'datatype', '@value'] ,
		'entitytype': ['rawname', 'description', 'name', 'icon', 'datatype', '@value'] ,
		'entityrole': ['rawname', 'hirable', 'femalename', 'tier', 'integer', 'description', 'type', 'tiers', 'name', 'pluralname', 'tag'] ,
		'npctemplate': ['npctemplateentry'] ,
		'skilltype': ['integer'] ,
		'controlpost': ['rawname', 'integer', 'description', 'type', 'skilltypes', 'name', 'icon', 'skillrelevance', 'tag'] ,
		'assignment': ['rawname', 'description', 'list', 'name', 'icon'] ,
		'controlposition': ['controlposition', 'tag', 'entity'] ,
		'objective': ['datatype', '@value'] ,
		'missiontype': ['integer'] ,
		'missiongroup': ['rawname', 'description', 'id', 'name', 'faction', 'datatype', '@value'] ,
		'level': ['integer', 'level'] ,
		'alertlevel': ['datatype', '@value'] ,
		'unitcategory': ['unitcategory', 'maxmk', 'mk', 'name'] ,
		'deployablecategory': ['maxmk', 'mk', 'name', 'deployablecategory'] ,
		'command': ['param', 'param2', 'value', 'datatype', '@value'] ,
		'commandaction': ['value', 'datatype', 'param', '@value'] ,
		'roompopulationtype': ['datatype', '@value'] ,
		'purpose': ['datatype', '@value'] ,
		'controlpaneltype': ['name', 'boolean', 'requireditems'] ,
		'signalleaktype': ['datatype', '@value'] ,
		'boardingphase': ['boardingphase', 'datatype', '@value'] ,
		'boardingbehaviour': ['boardingbehaviour', 'datatype', '@value'] ,
		'moodlevel': ['datatype', '@value'] ,
		'waretransport': ['list', 'name', 'waretransport', 'datatype', '@value'] ,
		'orderstate': ['datatype', '@value'] ,
		'cuestate': ['datatype', '@value'] ,
		'race': ['rawname', 'description', 'workforce', 'id', 'capacity', 'name', 'race'] ,
		'macro': ['numpierdocks', 'ispiratebase', 'icon', 'numdocks', 'consumptionvolume', 'isplayeronly', 'unitcategory', 'canclaimownership', 'primarypurpose', 'maxradarrange', 'istradingallowed', 'isheadquarters', 'docksizes', 'productionvolume', 'docksize', 'products', 'cargocapacity', 'isfriendfoe', 'purposename', 'isdeployable', 'cargo', 'workforce', 'isventureronly', 'islasertower', 'purposemacro', 'isbuildingallowed', 'boundingbox', 'hascontrolpanel', 'boolean', 'ware', 'isunit', 'isstorage', 'ismacro', 'isventuremodule', 'deployablecategory'] ,
		'tag': ['integer', 'tag'] ,
		'table': ['clone', 'keys', 'table', 'key', 'datatype'] ,
		'group': ['count', 'numeric', 'random', 'list', 'indexof', 'datatype', 'tag'] ,
		'componentslot': ['length'] ,
		'constructionsequence': ['count', 'numeric', 'constructionsequence', 'constructionplanentryid', 'datatype'] ,
		'loadout': ['wares', 'string', 'datatype', 'loadout'] ,
		'licence': ['boolean'] ,
		'quadrant': ['hitpoints', 'inverse'] ,
		'unlock': ['allowedowners', 'rawname', 'allowedwares', 'maxrelation', 'description', 'id', 'name', 'secrecylevel', '@id', 'datatype', 'minrelation'] ,
		'weaponmode': ['turrets'] ,
		'dockstate': ['dockstate', 'datatype', '@value'] ,
		'shiptype': ['description', 'name', 'datatype', '@value'] ,
		'roomtype': ['datatype', '@value'] ,
		'none': ['quadrant'] ,
		'up': ['quadrant'] ,
		'down': ['quadrant'] ,
		'left': ['quadrant'] ,
		'right': ['quadrant'] ,
		'front': ['quadrant'] ,
		'back': ['quadrant'] ,
		'@value': ['weaponmode', 'purpose', 'formationshape', 'orderstate', 'cuestate', 'attention', 'dockstate', 'controlpost', 'flightcontrolmodel', 'roompopulationtype', 'unitcategory', 'skilltype', 'missiontype', 'killmethod', 'missiongroup', 'entityrole', 'controlpaneltype', 'alertlevel', 'flightbehaviour', 'boardingphase', 'relationchangereason', 'signalleaktype', 'objective', 'commandaction', 'shiptype', 'level', 'boardingbehaviour', 'waretransport', 'controlposition', 'roomtype', 'class', 'componentstate', 'command', 'activity', 'entitytype', 'assignment', 'moodlevel', 'deployablecategory'] ,
		'warebasket': ['warelist', '@id'] ,
		'waregroup': ['@id'] ,
		'<macroname>': ['boolean', 'macro'] ,
		'<tagname>': ['tag'] ,
		'enum': ['tag'] ,
		'lookup': ['@name'] ,
		'@name': ['lookuplist'] ,
		'event': ['param3', 'name', 'param2', 'param', 'object'] ,
		'quota': ['missiontype'] ,
		'<missiontypename>': ['integer'] ,
		'<cuename>': ['cue'] ,
		'issurfaceelement': ['boolean'] ,
		'state': ['componentstate', 'cuestate', 'orderstate'] ,
		'parent': ['cue', 'component'] ,
		'defensible': ['shields', 'freebuildprocessor', 'ammostorage', 'boardingresistance', 'defensible', 'planmodule', 'buildprocessor', 'constructionsequence', 'boardingoperation', 'isenemylockingon', 'maxcombatrange', 'dps', 'ismissileincoming', 'boardingstrength', 'hasweaponmod', 'allmarinesdispatched', 'boardingbehaviour', 'isalertlevel', 'buildprocessors', 'buildmodule', 'units', 'freebuildprocessors', 'boardingoperations', 'turrets', 'buildmodules', 'availableunits', 'iscapturable', 'boardingmarines', 'hasshieldmod'] ,
		'object': ['boolean', 'container', 'object'] ,
		'hascontext': ['component'] ,
		'commoncontext': ['component'] ,
		'seed': ['largeint'] ,
		'knownname': ['string'] ,
		'velocity': ['vector'] ,
		'speed': ['length'] ,
		'relvelocity': ['vector'] ,
		'relspeed': ['length'] ,
		'size': ['length'] ,
		'height': ['length'] ,
		'width': ['length'] ,
		'owner': ['faction', 'container'] ,
		'coverowner': ['faction'] ,
		'trueowner': ['faction'] ,
		'isplayerowned': ['boolean'] ,
		'isownerless': ['boolean'] ,
		'distanceto': ['[$component, $position]', 'vector', 'component', 'position', 'componentslot'] ,
		'[$component, $position]': ['length'] ,
		'bboxdistanceto': ['[$component, $position]', 'component', '[$component, $position, $sizeobject]', 'position', 'componentslot'] ,
		'[$component, $position, $sizeobject]': ['length'] ,
		'gatedistance': ['component'] ,
		'relationto': ['faction', 'component'] ,
		'relationchange': ['attacktolerance', 'attackboost', 'attackfaction', 'policefaction', 'repairfaction', 'repairboost', 'killfaction', 'killboost'] ,
		'attacktolerance': ['change', 'decay', 'delay', 'threshold', 'absolute'] ,
		'threshold': ['float'] ,
		'absolute': ['float'] ,
		'change': ['float'] ,
		'decay': ['float'] ,
		'delay': ['time'] ,
		'attackboost': ['decay', 'delay', 'change', 'absolute'] ,
		'attackfaction': ['scan', 'hack'] ,
		'scan': ['float'] ,
		'hack': ['float'] ,
		'killboost': ['decay', 'delay', 'change', 'absolute'] ,
		'killfaction': ['bonus', 'change'] ,
		'bonus': ['float'] ,
		'policefaction': ['hack', 'change', 'bounty', 'scan', 'faction'] ,
		'bounty': ['money'] ,
		'repairboost': ['change', 'absolute'] ,
		'repairfaction': ['change'] ,
		'mayattack': ['faction', 'component'] ,
		'description': ['string'] ,
		'response': ['description', 'rawname', 'name', 'id'] ,
		'shouldaskplayer': ['boolean'] ,
		'revealedpercentage': ['integer'] ,
		'revealedlevelpercentage': ['level'] ,
		'<infotype>': ['boolean'] ,
		'scannedlevel': ['integer'] ,
		'maxlegalscanlevel': ['faction', 'component'] ,
		'secrecylevel': ['integer', 'max', 'min'] ,
		'haswaypoint': ['list'] ,
		'haswaypointpath': ['list'] ,
		'destructible': ['maxshield', 'modulesets', 'hasstorage', 'canclaimownership', 'primarypurpose', 'productions', 'maxhull', 'shield', 'hullpercentage', 'drop', 'isfunctional', 'shieldpercentage', 'hull'] ,
		'isfunctional': ['boolean'] ,
		'hull': ['hitpoints'] ,
		'maxhull': ['hitpoints'] ,
		'hullpercentage': ['float'] ,
		'shield': ['hitpoints'] ,
		'maxshield': ['hitpoints'] ,
		'shieldpercentage': ['float'] ,
		'hasstorage': ['boolean'] ,
		'canclaimownership': ['boolean'] ,
		'productions': ['list'] ,
		'modulesets': ['list'] ,
		'primarypurpose': ['purpose'] ,
		'formationleader': ['object'] ,
		'idcode': ['string'] ,
		'isformationleader': ['boolean'] ,
		'isformationwingman': ['boolean'] ,
		'iscommandeerable': ['boolean'] ,
		'iscommandeered': ['boolean'] ,
		'isgodobject': ['boolean'] ,
		'ismasstraffic': ['boolean'] ,
		'ishighwaytraffic': ['boolean'] ,
		'istemptraffic': ['boolean'] ,
		'iszonechangepending': ['boolean'] ,
		'numwaypoints': ['integer'] ,
		'maxradarrange': ['length'] ,
		'region': ['region'] ,
		'ismission': ['boolean'] ,
		'suspicious': ['boolean'] ,
		'isradarvisible': ['boolean'] ,
		'canbepickedup': ['boolean'] ,
		'canbepickedupby': ['ship'] ,
		'boost': ['maxduration', 'chargetime', 'rechargetime', 'available', 'maxspeed', 'active'] ,
		'maxspeed': ['length'] ,
		'travel': ['active', 'available', 'chargetime'] ,
		'chargetime': ['time'] ,
		'value': ['integer'] ,
		'repairprice': ['money'] ,
		'count': ['integer'] ,
		'random': ['ware', 'shieldgenerator', 'turret', 'adsign', 'destructible'] ,
		'numsignalleakslots': ['integer'] ,
		'scuttleeffect': ['string'] ,
		'isonlineobject': ['boolean'] ,
		'masstrafficstartobject': ['object'] ,
		'masstrafficendobject': ['object'] ,
		'hasenginemod': ['ware', 'boolean'] ,
		'haspaintmod': ['ware', 'boolean'] ,
		'spawnsourceseed': ['largeint'] ,
		'isunit': ['boolean'] ,
		'isdeployable': ['boolean'] ,
		'formationradius': ['length'] ,
		'isformationrolling': ['boolean'] ,
		'isformationrollmembers': ['boolean'] ,
		'formationmaxshipsperline': ['formationshape'] ,
		'mine': ['isfriendfoe', 'friendlist', 'target', 'foelist'] ,
		'isfriendfoe': ['boolean'] ,
		'friendlist': ['list'] ,
		'foelist': ['list'] ,
		'pilot': ['entity'] ,
		'assignedpilot': ['entity'] ,
		'defencenpc': ['entity'] ,
		'tradenpc': ['entity'] ,
		'engineer': ['entity'] ,
		'shiptrader': ['entity'] ,
		'shadyguy': ['entity'] ,
		'controlentity': ['controlpost', 'default'] ,
		'default': ['warelist', 'string', 'entity'] ,
		'assignedcontrolentity': ['controlpost', 'default'] ,
		'canhavecontrolentity': ['controlpost'] ,
		'controlpostslot': ['controlpost'] ,
		'nextorder': ['order'] ,
		'defaultorder': ['order'] ,
		'orders': ['list'] ,
		'tradeorders': ['list'] ,
		'commander': ['controllable', 'boolean'] ,
		'commanderentity': ['entity'] ,
		'subordinates': ['list', 'assignment'] ,
		'allsubordinates': ['list'] ,
		'canhavecommander': ['component'] ,
		'wing': ['name', 'iscommander', 'commander'] ,
		'iscommander': ['boolean'] ,
		'controlposts': ['all', 'free', 'entity'] ,
		'all': ['hitpoints', 'integer', 'list', 'length'] ,
		'free': ['solid', 'integer', 'list', 'liquid', 'universal', 'all', 'container'] ,
		'controlroom': ['room'] ,
		'hackerprobe': ['hackduration', 'hackerprobe'] ,
		'software': ['compatible', 'installed', 'default'] ,
		'compatible': ['warelist'] ,
		'installed': ['warelist'] ,
		'people': ['count', 'npctemplate', 'list', 'entityrole', 'capacity', 'free'] ,
		'capacity': ['solid', 'integer', 'liquid', 'universal', 'all', 'container', 'tag'] ,
		'combinedskill': ['integer'] ,
		'potentialskill': ['controlpost', 'entityrole'] ,
		'ischairslot': ['componentslot'] ,
		'chairapproachslot': ['componentslot'] ,
		'chairbaseslot': ['componentslot'] ,
		'roomslot': ['componentslot'] ,
		'controlpositions': ['list'] ,
		'tradecomputer': ['entity'] ,
		'iscapturable': ['boolean'] ,
		'<alertlevel>': ['boolean'] ,
		'boardingoperation': ['operation'] ,
		'boardingoperations': ['list'] ,
		'boardingmarines': ['count', 'level', 'combinedskill'] ,
		'allmarinesdispatched': ['boolean'] ,
		'boardingresistance': ['integer'] ,
		'boardingstrength': ['integer'] ,
		'planmodule': ['constructionplanentryid'] ,
		'constructionplanentryid': ['constructionplanentrydata'] ,
		'dps': ['lasers', 'secondary', 'turrets', 'missiles', 'primary', 'all'] ,
		'lasers': ['primary', 'all', 'secondary'] ,
		'missiles': ['primary', 'all', 'secondary'] ,
		'turrets': ['fortarget', 'quadrant', 'all', 'length'] ,
		'<quadrantname>': ['hitpoints'] ,
		'fortarget': ['object'] ,
		'maxcombatrange': ['lasers', 'weaponmode', 'secondary', 'turrets', 'missiles', 'primary', 'all'] ,
		'units': ['count', 'collect', 'unitcategory', 'maxcount', 'macro', 'free'] ,
		'maxcount': ['integer'] ,
		'collect': ['count', 'ware'] ,
		'mk': ['i'] ,
		'i': ['list'] ,
		'availableunits': ['count', 'collect', 'unitcategory', 'macro'] ,
		'ammostorage': ['ware', 'missile', 'macro', 'countermeasure', 'deployable', 'deployablecategory'] ,
		'missile': ['count', 'target', 'capacity', 'free', 'basecapacity'] ,
		'basecapacity': ['integer'] ,
		'countermeasure': ['basecapacity', 'count', 'free', 'capacity'] ,
		'deployable': ['basecapacity', 'count', 'free', 'capacity'] ,
		'isenemylockingon': ['boolean'] ,
		'ismissileincoming': ['boolean'] ,
		'hasweaponmod': ['ware', 'boolean', 'macro'] ,
		'hasshieldmod': ['ware', 'groupcontext', 'boolean'] ,
		'groupcontext': ['grouptag'] ,
		'grouptag': ['ware'] ,
		'buildmodule': ['isbusy', 'freebuildprocessor', 'requiresconstructionvessel', 'dock', 'constructingcomponents', 'canbuildmacro', 'isbuilding', 'iswaitingforresources', 'canequipclass', 'canbuildequipment', 'constructionvessel', 'buildprocessor', 'canbuildclass', 'buildmacros', 'buildships', 'iswaitingforstorage', 'constructionvesseldeployed', 'iswaitingforconstructionvessel', 'buildanchor', 'buildprocessors', 'buildequipment', 'buildmodule', 'freebuildprocessors', 'constructingmodule', 'buildstorage', 'freedock'] ,
		'buildmodules': ['list'] ,
		'buildprocessor': ['isbusy', 'recycled', 'requiresconstructionvessel', 'constructingcomponents', 'neededslotresources', 'canbuildmacro', 'isbuilding', 'iswaitingforresources', 'canequipclass', 'laststepresources', 'canbuildequipment', 'stepresources', 'buildprocessor', 'elapsedsteptime', 'canbuildclass', 'buildmacros', 'neededsequenceresources', 'totaltime', 'buildships', 'iswaitingforstorage', 'iswaitingforconstructionvessel', 'currentslotresources', 'canabortbuild', 'buildanchor', 'buildequipment', 'buildmodule', 'build', 'constructingmodule', 'steptime', 'elapsedtime'] ,
		'buildprocessors': ['list'] ,
		'freebuildprocessor': ['buildprocessor'] ,
		'freebuildprocessors': ['list'] ,
		'hasmasstraffic': ['boolean'] ,
		'hasunitdrone': ['ship'] ,
		'<trafficlevel>': ['boolean'] ,
		'buildingmodule': ['buildmodule'] ,
		'buildingprocessor': ['buildprocessor'] ,
		'builds': ['queued', 'inprogress'] ,
		'queued': ['list'] ,
		'inprogress': ['list'] ,
		'buildanchor': ['component'] ,
		'buildequipment': ['wares', 'excluded', 'included'] ,
		'excluded': ['warelist'] ,
		'included': ['warelist'] ,
		'buildships': ['wares', 'excluded', 'included'] ,
		'canbuildclass': ['class'] ,
		'canequipclass': ['class'] ,
		'canbuildequipment': ['ware', 'list'] ,
		'canbuildmacro': ['macro'] ,
		'canbuildships': ['boolean'] ,
		'canequipships': ['boolean'] ,
		'canabortbuild': ['build', 'boolean'] ,
		'plannedconstruction': ['sequence', 'boundingbox'] ,
		'sequence': ['constructionsequence'] ,
		'boundingbox': ['max', 'center', 'exists'] ,
		'max': ['float', 'ware', 'numeric', 'integer', 'vector'] ,
		'center': ['vector'] ,
		'cargo': ['ware', 'cargolist', 'tags', 'capacity'] ,
		'products': ['warelist', 'ware'] ,
		'dockingenabled': ['boolean'] ,
		'dockingallowed': ['ship'] ,
		'intermediate': ['boolean'] ,
		'resources': ['warelist', 'ware', 'wareamountlist'] ,
		'tradewares': ['warelist'] ,
		'buyprice': ['ware'] ,
		'sellprice': ['ware'] ,
		'buildprice': ['ware'] ,
		'productionmoney': ['money'] ,
		'wantedmoney': ['money'] ,
		'istraderestricted': ['ware', 'boolean'] ,
		'hastradesubscription': ['boolean'] ,
		'haspermanenttradesubscription': ['boolean'] ,
		'supplies': ['wareamountlist'] ,
		'supplyorders': ['wareamountlist'] ,
		'workforce': ['resources', 'amount', 'bonus', 'capacities', 'min', 'optimal', 'capacity', 'race', 'races', 'amounts'] ,
		'races': ['list'] ,
		'amounts': ['table'] ,
		'capacities': ['table'] ,
		'optimal': ['integer'] ,
		'min': ['integer', 'numeric', 'float'] ,
		'hasownaccount': ['boolean'] ,
		'minbudget': ['money'] ,
		'maxbudget': ['money'] ,
		'loadoutlevel': ['float'] ,
		'buildpricefactor': ['float'] ,
		'isbuildrestricted': ['faction'] ,
		'type': ['shiptype', 'string', 'controlpaneltype', 'entitytype', 'roomtype', 'signalleaktype'] ,
		'typename': ['string'] ,
		'numfreeactorslots': ['integer'] ,
		'actors': ['list'] ,
		'assigneddock': ['dockingbay'] ,
		'docksize': ['integer'] ,
		'dock': ['dockingbay', 'docksize'] ,
		'dockslot': ['componentslot'] ,
		'maxyawspeed': ['angle'] ,
		'maxpitchspeed': ['angle'] ,
		'maxrollspeed': ['angle'] ,
		'canenterhighway': ['boolean'] ,
		'parkedat': ['destructible'] ,
		'pickedupobject': ['object'] ,
		'job': ['string'] ,
		'isjobship': ['boolean'] ,
		'isrequestedjobship': ['boolean'] ,
		'jobexpired': ['boolean'] ,
		'jobcommander': ['ship'] ,
		'jobmainzone': ['zone'] ,
		'jobsubordinates': ['invalid', 'valid'] ,
		'valid': ['list'] ,
		'invalid': ['list'] ,
		'encounterid': ['string'] ,
		'isencountership': ['boolean'] ,
		'constructionmodule': ['buildmodule'] ,
		'isdeployedconstructionvessel': ['boolean'] ,
		'iscapitalship': ['boolean'] ,
		'islasertower': ['boolean'] ,
		'hasshipmod': ['ware', 'boolean'] ,
		'canbeclaimed': ['boolean'] ,
		'defaultformationradius': ['ship'] ,
		'buildplot': ['max', 'center', 'exists'] ,
		'paidbuildplot': ['max', 'center', 'exists'] ,
		'buildstorage': ['base', 'buildstorage'] ,
		'istradestation': ['boolean'] ,
		'isshipyard': ['boolean'] ,
		'iswharf': ['boolean'] ,
		'isequipmentdock': ['boolean'] ,
		'isdefencestation': ['boolean'] ,
		'ispiratebase': ['boolean'] ,
		'isheadquarters': ['boolean'] ,
		'isfactionheadquarters': ['boolean'] ,
		'gate': ['isactive', 'destination', 'isaccelerator', 'exit'] ,
		'destination': ['zone'] ,
		'exit': ['highwayexitgate', 'gate'] ,
		'isaccelerator': ['boolean'] ,
		'isactive': ['boolean'] ,
		'highwayentrygate': ['destination', 'highway', 'exit'] ,
		'highway': ['junctions', 'highway', 'islocalhighway', 'issuperhighway', 'destination', 'origin', 'entry', 'exit', 'closestpointtoplayer'] ,
		'highwayexitgate': ['highway', 'entry'] ,
		'entry': ['highwayentrygate'] ,
		'resourceprobe': ['currentyield', 'maxyield'] ,
		'currentyield': ['wareamountlist'] ,
		'maxyield': ['wareamountlist'] ,
		'collectableammo': ['ammo'] ,
		'ammo': ['count', 'ware', 'iscompatible', 'capacity', 'macro'] ,
		'collectablewares': ['money', 'unbundle'] ,
		'unbundle': ['boolean'] ,
		'base': ['ware', 'float', 'container', 'station'] ,
		'navcontext': ['isprivate'] ,
		'isprivate': ['boolean'] ,
		'isbusy': ['boolean'] ,
		'isbuilding': ['boolean'] ,
		'buildmacros': ['list'] ,
		'constructingcomponents': ['list'] ,
		'constructingmodule': ['component'] ,
		'requiresconstructionvessel': ['boolean'] ,
		'iswaitingforconstructionvessel': ['boolean'] ,
		'iswaitingforresources': ['boolean'] ,
		'iswaitingforstorage': ['boolean'] ,
		'constructionvessel': ['ship'] ,
		'constructionvesseldeployed': ['boolean'] ,
		'freedock': ['docksize'] ,
		'elapsedtime': ['time'] ,
		'elapsedsteptime': ['time'] ,
		'steptime': ['time'] ,
		'totaltime': ['time'] ,
		'currentslotresources': ['wareamountlist'] ,
		'stepresources': ['wareamountlist'] ,
		'laststepresources': ['wareamountlist'] ,
		'neededslotresources': ['wareamountlist'] ,
		'neededsequenceresources': ['wareamountlist'] ,
		'recycled': ['wareamountlist'] ,
		'connectionmodule': ['isventuremodule'] ,
		'isventuremodule': ['boolean'] ,
		'ventureplatform': ['ventureplatform', 'venturedocks'] ,
		'venturedocks': ['list'] ,
		'habitationmodule': ['workforce'] ,
		'pier': ['numpierdocks'] ,
		'numpierdocks': ['integer'] ,
		'production': ['resources', 'products', 'isproducing'] ,
		'isproducing': ['boolean'] ,
		'storagemodule': ['waretransport', 'cargo'] ,
		'engine': ['travel', 'boost'] ,
		'rechargetime': ['time'] ,
		'maxduration': ['time'] ,
		'crate': ['money'] ,
		'hackduration': ['time'] ,
		'controlpanel': ['type', 'requireditems'] ,
		'requireditems': ['wareamountlist'] ,
		'signalleak': ['islocked', 'type'] ,
		'islocked': ['boolean'] ,
		'dockarea': ['ventureplatform', 'isventuremodule', 'dockarea'] ,
		'walkablemodule': ['entrypos', 'exitpos', 'hasentrypos', 'hasexitpos', 'walkablemodule', 'numdocks'] ,
		'freemissionactorslot': ['boolean'] ,
		'slotcontext': ['component'] ,
		'hascontrolpanel': ['controlpaneltype'] ,
		'dockingbay': ['isdockingallowed', 'launchpos', 'isplayeronly', 'ventureplatform', 'isventureronly', 'isundockingallowed', 'istradingallowed', 'assignedship', 'docksize', 'maxoffset', 'isstorage', 'external', 'dockstate', 'docked', 'dockslot', 'todockpos', 'isbuildingallowed'] ,
		'assignedship': ['ship'] ,
		'maxoffset': ['sizetag'] ,
		'sizetag': ['rotation'] ,
		'docked': ['list'] ,
		'external': ['boolean'] ,
		'isstorage': ['boolean'] ,
		'isdockingallowed': ['boolean'] ,
		'isundockingallowed': ['boolean'] ,
		'todockpos': ['position'] ,
		'launchpos': ['position'] ,
		'isbuildingallowed': ['boolean'] ,
		'istradingallowed': ['boolean'] ,
		'isplayeronly': ['boolean'] ,
		'isventureronly': ['boolean'] ,
		'hasentrypos': ['boolean'] ,
		'entrypos': ['position'] ,
		'hasexitpos': ['boolean'] ,
		'exitpos': ['position'] ,
		'numdocks': ['docksize'] ,
		'space': ['security', 'economy', 'sunlight'] ,
		'economy': ['float'] ,
		'security': ['float'] ,
		'sunlight': ['largefloat'] ,
		'isnormalcluster': ['boolean'] ,
		'ispresentation': ['boolean'] ,
		'systemid': ['integer'] ,
		'iscontested': ['boolean'] ,
		'iscontestedby': ['faction'] ,
		'contestingfactions': ['list'] ,
		'adjacentzones': ['list'] ,
		'haspriority': ['boolean'] ,
		'istempzone': ['boolean'] ,
		'isnormalzone': ['boolean'] ,
		'islocalhighway': ['boolean'] ,
		'issuperhighway': ['boolean'] ,
		'origin': ['zone'] ,
		'junctions': ['list'] ,
		'closestpointtoplayer': ['position'] ,
		'customhandler': ['boolean'] ,
		'role': ['entityrole'] ,
		'page': ['integer'] ,
		'isfemale': ['boolean'] ,
		'isavatar': ['boolean'] ,
		'iscommable': ['boolean'] ,
		'ismissionactor': ['boolean'] ,
		'isremotecommable': ['boolean'] ,
		'iscontrolentity': ['boolean'] ,
		'isintransit': ['boolean'] ,
		'istemporary': ['boolean'] ,
		'ishidden': ['boolean'] ,
		'iswalking': ['boolean'] ,
		'slowwalkspeed': ['float'] ,
		'walkspeed': ['float'] ,
		'runspeed': ['float'] ,
		'isinspeakrange': ['boolean', 'entity'] ,
		'experienceprogress': ['integer'] ,
		'neededexperience': ['integer'] ,
		'skill': ['skilltype'] ,
		'<skillname>': ['integer'] ,
		'skillsvisible': ['boolean'] ,
		'assignedcontrolled': ['controllable'] ,
		'inventory': ['wareamountlist'] ,
		'stock': ['warelist'] ,
		'cancraft': ['ware'] ,
		'shouldinformplayer': ['boolean'] ,
		'shouldwarnplayer': ['boolean'] ,
		'istradecomputer': ['boolean'] ,
		'isshadyguy': ['boolean'] ,
		'tradesvisible': ['boolean'] ,
		'npc': ['targetslot', 'hastool', 'npctemplate', 'currentchair', 'hasclothingmod'] ,
		'targetslot': ['componentslot'] ,
		'currentchair': ['componentslot'] ,
		'hastool': ['boolean'] ,
		'weapon': ['mode', 'ammo', 'isreadytofire'] ,
		'iscompatible': ['macro'] ,
		'isreadytofire': ['boolean'] ,
		'mode': ['weaponmode'] ,
		'tags': ['list'] ,
		'offset': ['position'] ,
		'staticoffset': ['position'] ,
		'staticrotation': ['rotation'] ,
		'macroslot': ['staticoffset', 'rotation', 'macro', 'name', 'tags', 'offset', 'staticrotation'] ,
		'buyer': ['container'] ,
		'seller': ['container'] ,
		'ispricelocked': ['container'] ,
		'desiredamount': ['integer'] ,
		'offeramount': ['integer', 'object'] ,
		'minamount': ['integer'] ,
		'transferredamount': ['integer'] ,
		'destroyedamount': ['integer'] ,
		'volume': ['integer'] ,
		'minvolume': ['integer'] ,
		'price': ['money'] ,
		'unitprice': ['money'] ,
		'minprice': ['money'] ,
		'relativeprice': ['float'] ,
		'quantityfactor': ['float'] ,
		'stocklevel': ['float'] ,
		'bundle': ['boolean'] ,
		'buyfree': ['boolean', 'object'] ,
		'sellfree': ['boolean', 'object'] ,
		'iswareexchange': ['boolean'] ,
		'isshiptoship': ['boolean'] ,
		'isbuyerpassive': ['boolean'] ,
		'issellerpassive': ['boolean'] ,
		'ispassive': ['container'] ,
		'exchangepartner': ['container'] ,
		'restriction': ['inverted', 'faction'] ,
		'inverted': ['boolean'] ,
		'isshipbuild': ['boolean'] ,
		'isexpansion': ['boolean'] ,
		'isupgrade': ['boolean'] ,
		'mayrequireconstructionvessel': ['boolean'] ,
		'buildobject': ['container'] ,
		'construction': ['container'] ,
		'consumables': ['table'] ,
		'boardee': ['defensible'] ,
		'attackers': ['list'] ,
		'marines': ['fighting', 'killed', 'infiltrating'] ,
		'infiltrating': ['count', 'npctemplate', 'list', 'combinedskill'] ,
		'fighting': ['count', 'npctemplate', 'list', 'combinedskill'] ,
		'killed': ['count', 'npctemplate', 'list', 'combinedskill'] ,
		'boardingapproachthreshold': ['integer'] ,
		'boardinginsertionthreshold': ['integer'] ,
		'minrelation': ['float'] ,
		'precursor': ['string'] ,
		'issellable': ['boolean'] ,
		'indexof': ['value', 'component'] ,
		'canplayercancel': ['boolean'] ,
		'isinfinite': ['boolean'] ,
		'isrunning': ['boolean'] ,
		'<param>': ['boolean'] ,
		'numeric': ['uivalue'] ,
		'constructionplanentrydata': ['loadout', 'id', 'exists', 'macro'] ,
		'clone': ['table', 'list'] ,
		'average': ['numeric'] ,
		'keys': ['count', 'random', 'numeric', 'list', 'sorted'] ,
		'sorted': ['list'] ,
		']': ['string'] ,
		'x': ['length'] ,
		'y': ['length'] ,
		'z': ['length'] ,
		'yaw': ['angle'] ,
		'pitch': ['angle'] ,
		'roll': ['angle'] ,
		'inverse': ['quadrant', 'rotation'] ,
		'primaryrace': ['race'] ,
		'knowntoplayer': ['boolean'] ,
		'mid': ['float'] ,
		'relation': ['numeric'] ,
		'uivalue': ['integer'] ,
		'haslicence': ['licence'] ,
		'canholdlicence': ['licence'] ,
		'licences': ['list'] ,
		'heldlicences': ['list'] ,
		'<licencetype>': ['licence'] ,
		'<moodtype>': ['moodlevel'] ,
		'isaggressive': ['boolean'] ,
		'iseconomic': ['boolean'] ,
		'ispolice': ['boolean'] ,
		'isprotective': ['boolean'] ,
		'willclaimspace': ['boolean'] ,
		'representative': ['entity'] ,
		'icon': ['string'] ,
		'averageprice': ['money'] ,
		'maxprice': ['money'] ,
		'pricerange': ['money'] ,
		'transporttag': ['tag'] ,
		'buyrestriction': ['base', 'faction'] ,
		'sellrestriction': ['base', 'faction'] ,
		'isinventory': ['boolean'] ,
		'isammo': ['boolean'] ,
		'iscargo': ['boolean'] ,
		'iscrafting': ['boolean'] ,
		'isvolatile': ['boolean'] ,
		'isgift': ['boolean'] ,
		'israre': ['boolean'] ,
		'isdropallowed': ['boolean'] ,
		'isresearchable': ['boolean'] ,
		'illegal': ['boolean'] ,
		'illegalto': ['faction'] ,
		'{null': ['boolean'] ,
		'objectmacro': ['macro'] ,
		'objectcount': ['integer'] ,
		'issoftware': ['boolean'] ,
		'softwareversion': ['next', 'base', 'max', 'previous'] ,
		'next': ['ware'] ,
		'previous': ['ware'] ,
		'isweaponmod': ['boolean'] ,
		'isenginemod': ['boolean'] ,
		'isshieldmod': ['boolean'] ,
		'isshipmod': ['boolean'] ,
		'isequipmentmod': ['boolean'] ,
		'equipmentmodquality': ['boolean'] ,
		'ispaintmod': ['boolean'] ,
		'paintmodquality': ['boolean'] ,
		'isclothingmod': ['boolean'] ,
		'clothingmodquality': ['boolean'] ,
		'research': ['unlocked', 'precursors', 'requiredprecursors'] ,
		'unlocked': ['boolean'] ,
		'precursors': ['warelist'] ,
		'requiredprecursors': ['warelist'] ,
		'lookuplist': ['count', 'list', 'random', 'index'] ,
		'warelist': ['count', 'random', 'list', 'ware'] ,
		'wareamountlist': ['count', 'ware', 'table', 'random', 'list', 'illegalto', 'illegal'] ,
		'cargolist': ['ware', 'tags', 'free', 'capacity'] ,
		'liquid': ['integer'] ,
		'solid': ['integer'] ,
		'universal': ['integer'] ,
		'npctemplateentry': ['isbusy', 'isfemale', 'istemporary', 'isremotecommable', 'tradesvisible', 'skillsvisible', 'ismissionactor', 'customhandler', 'page', 'macro', 'combinedskill', 'name', 'role', 'skill', 'potentialskill', 'race', 'isintransit', 'exists', 'seed'] ,
		'ismacro': ['list', 'macro'] ,
		'purposemacro': ['macro'] ,
		'purposename': ['string'] ,
		'docksizes': ['list'] ,
		'productionvolume': ['integer'] ,
		'consumptionvolume': ['integer'] ,
		'cargocapacity': ['integer'] ,
		'allowedowners': ['list'] ,
		'allowedwares': ['list'] ,
		'maxrelation': ['float'] ,
		'version': ['integer'] ,
		'static': ['cue'] ,
		'staticbase': ['cue'] ,
		'namespace': ['cue'] ,
		'library': ['cue'] ,
		'isinstance': ['boolean'] ,
		'hasmissionoffer': ['boolean'] ,
		'hasmission': ['boolean'] ,
		'hasguidance': ['boolean'] ,
		'offerlocations': ['list'] ,
		'canactivatesubmission': ['cue'] ,
		'actor': ['nonplayer'] ,
		'isnumeric': ['boolean'] ,
		'isstring': ['boolean'] ,
		'femalename': ['string'] ,
		'pluralname': ['string'] ,
		'hirable': ['boolean'] ,
		'tiers': ['list'] ,
		'tier': ['level'] ,
		'skilltypes': ['list'] ,
		'skillrelevance': ['skilltype'] ,
		'maxmk': ['integer'] ,
		'formatted': ['string', 'default'] ,
		'boolean': ['true', 'false'] ,
		};

	// Use the console to output diagnostic information (console.log) and errors (console.error)
	// This line of code will only be executed once when your extension is activated

 
	// The command has been defined in the package.json file
	// Now provide the implementation of the command with registerCommand
	// The commandId parameter must match the command field in package.json
	function buildResults(last:string, complete: string, items:vscode.CompletionItem[], depth:number){
		
		if (depth > 3){
			return;
		}

		if (!(last in data)){
			for (const possiblePartial in data) {
				if (possiblePartial.indexOf(last)>-1){
					let nextComplete = complete+"."+possiblePartial;
					if (nextComplete !== ""){
						items.push(new vscode.CompletionItem(nextComplete));
					}
					buildResults(nextComplete,nextComplete, items, depth+1);
				}
			}
			if (complete !== ""){
				items.push(new vscode.CompletionItem(complete));
			}
			return;
		}
		items.push(new vscode.CompletionItem(complete));
		var nexts = (data as any)[last];
		for (const next in nexts) {
			let nextComplete = complete+"."+nexts[next];
			buildResults(next,nextComplete, items, depth+1);
		}
	}
	let sel: vscode.DocumentSelector = { language: 'xml' };
	let provider: vscode.CompletionItemProvider = {
		provideCompletionItems(document: vscode.TextDocument, position: vscode.Position) {

			// get all text until the `position` and check if it reads `console.`
			// and iff so then complete if `log`, `warn`, and `error`
			let prefix= document.lineAt(position).text.substr(0, position.character);

			let items: vscode.CompletionItem[]= [];
			let begin = prefix.lastIndexOf(".");
			if (begin === -1){
				begin = prefix.lastIndexOf(" ");
			}
			if (begin === -1){
				begin = prefix.lastIndexOf("\t");
			}
			let interesting = prefix.substr(begin+1);
			for (const possiblePartial in data) {
				if (possiblePartial.indexOf(interesting)>-1){
					items.push(new vscode.CompletionItem(possiblePartial));
					buildResults(possiblePartial, possiblePartial,items, 0);
				}
			}


			return items;
		}
	};
	let disposable = vscode.languages.registerCompletionItemProvider(sel,provider);

	context.subscriptions.push(disposable);
}

// this method is called when your extension is deactivated
export function deactivate() {}
